### PR TITLE
break out the scripts to be more user driven.

### LINKED ISSUE #126: Expand Ops Setup Guide
https://github.com/codefellows/ops-102-guide/pull/60

### PR DESCRIPTION
**Pull request by RogerHuba**
will close #126

### CODE REVIEW

**Comment by RogerHuba** [comment]
left script.md for previous reference and left the .sh files for now.  Can remove when we are ready

**Comment by brookr** [comment]
@marcorvazquezs Can you please test this new setup flow, and verify it's doing all the things we need it to do, and is written clearly so 102 students could follow along?

**Comment by brookr** [comment]
@marcorvazquezs Please also identify if anything from [this folder](https://github.com/codefellows/setup-guide/tree/main/configs/ops) is needed, that is not a part of the new setup PR.

**Review by marcorvazquezs — APPROVED** [review]
All looks good to me, awesome stuff @RogerHuba ! 🤟

**Pull request merged**
