### PR TITLE
add note about performance

### PR DESCRIPTION
**Pull request by RogerHuba**

### CODE REVIEW

**Review by brookr — APPROVED** [review]

**Review by brookr — APPROVED** [review]

**Review by brookr — CHANGES_REQUESTED** [review]
Let's just add that as the last command in .profile. Remove all references here.

**Comment by RogerHuba** [comment]
Closing PR.  Moving the cd~ directly to .profile.

**Comment by brookr** [comment]
Someone (sorry, can't remember who) suggested this might impact the VS Code built in terminal... which should open in the project dir by default, and not be redirected to `~`.

**Comment by brookr** [comment]
Ah Keith: https://github.com/codefellows/setup-guide/pull/91

**Pull request closed without merging**
